<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9df36eeb24edd7fce0df5a2e0548f026
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'Michelf\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Michelf\\' => 
        array (
            0 => __DIR__ . '/..' . '/michelf/php-markdown/Michelf',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9df36eeb24edd7fce0df5a2e0548f026::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9df36eeb24edd7fce0df5a2e0548f026::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
